### PR TITLE
update to work with atom 1.17.0 docks

### PR DESCRIPTION
**Pull request by chrisdrackett**

### CODE REVIEW

**Comment by chrisdrackett** [comment]
@susisu there is one open issue around pane indexes. I think because I'm only getting panes from the center in some places, but in other places it is looking at all the panes. I'm going to attempt to debug.

**Comment by chrisdrackett** [comment]
ok, for whatever reason this seems to be working now.

¯\_(ツ)_/¯

**Comment by chrisdrackett** [comment]
I was thinking that the name `working-files` works pretty well for this package, and is more usable now that its a dock item. I wonder if its worth looking into working with https://github.com/davidashman/working-files as his package is very similar to yours?

**Comment by susisu** [comment]
Hi @chrisdrackett
Thank you for your PR, but I'm sorry I can't merge it now.

I haven't decided yet how to adapt this package to the Dock system of the next version.
It looks you made this package working as a dock item independent to the tree view (right?),
but I really like the current style, working as a “parasite” on the tree view,
and I also would like to adopt it (perhaps as an optional way) if possible.

Anyway, your ideas are great and helpful for me.
Thanks a lot again!

**Comment by susisu** [comment]
There are two (or three) separate issues:

1. How to adapt to the next version
2. ... and its implementation
3. (Changing the package name?)

They should be considered respectively, so I close this PR for now.
See #2

**Pull request closed without merging**
